#!/usr/bin/env bash
# this Configure my Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo touch /etc/nginx/sites-available/hello_world.conf
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
redirect_me="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "60i\\$redirect_me" /etc/nginx/sites-enabled/default
sudo service nginx restart
