#!/usr/bin/env bash
# this Configure my Nginx server so that /redirect_me 
sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
redirect_me=\
"\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "60i\\$redirect_me" /etc/nginx/sites-enabled/default
sudo service nginx restart
