#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt-get -y install haproxy=2.8.\*
frontend="frontend front
    bind *:80
    mode http
    default_backend backservers"

backend="backend backservers
    balance roundrobin
    server 291203-web-01 100.24.255.23:80 check
    server 291203-web-02 54.234.80.214:80 check"

configurations="
$frontend

$backend"

sudo echo -e "$configurations" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart