#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

frontend="frontend front
    bind *:80
    default_backend back_servers"

backend="backend back_servers
    balance roundrobin
    server web_1 100.24.255.23:80 check
    server web_2 54.234.80.214:80 check"

configurations="
$frontend

$backend"

sudo echo "$configurations" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start