#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for ((i=1; i<=100; i++))
do
	((divt= i % 3))
	((divf= i % 5))
	if [[ $divt -eq 0 && $divf -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [ $divt -eq 0 ]
	then
		echo "fizz"
	elif [ $divf -eq 0 ]
	then
		echo "buzz"
	else
		echo "$i"
	fi
done
