#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server
file="/etc/hosts"
if [ ! -f "$file" ]; then
  echo "Error: $file not found."
  exit 1
fi
hosts=$(mktemp)
cp "$file" "$hosts"
if grep -q "localhost" "$file";
then
	sed -i 's/^127.0.0.1.*$/127.0.0.2       localhost/' "$hosts"
else
	echo "127.0.0.2 localhost" >> "$hosts"
fi

if grep -q "facebook.com" "$file";
then
	sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' "$hosts"
else
	echo "8.8.8.8 facebook.com" >> "$hosts"
fi
cp -f "$hosts" "$file"