#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine
ip=$(ip -o addr show | grep -E -o "inet ([0-9]{1,3}\.){3}[0-9]{1,3}")
ipv4=$(echo "$ip" | grep -E -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
echo "${ipv4}"
